# Generated by Django 4.2.12 on 2024-10-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطبان'},
        ),
    ]
